import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blogsum",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " max-w-6xl mx-auto p-6 lg:px-8"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
